use k256::{
    PublicKey, SecretKey,
    elliptic_curve::{
        group::GroupEncoding,
        sec1::ToEncodedPoint,
    },
    ProjectivePoint, Scalar,
};
use tiny_keccak::{Hasher, Keccak};

/// Relayer's long-lived keypairs (the "meta-address").
/// - spend keypair: used to derive stealth private keys
/// - view keypair: used for ECDH shared secret computation
#[derive(Clone)]
pub struct RelayerKeys {
    pub spend_privkey: SecretKey,
    pub spend_pubkey: PublicKey,
    pub view_privkey: SecretKey,
    pub view_pubkey: PublicKey,
}

/// An ephemeral keypair generated by the user for a single stealth transfer.
pub struct EphemeralKeys {
    pub privkey: SecretKey,
    pub pubkey: PublicKey,
}

/// A derived stealth address and associated data.
pub struct StealthAddress {
    /// The 20-byte Ethereum address derived from the stealth public key.
    pub address: [u8; 20],
    /// The stealth public key (used for verification).
    pub stealth_pubkey: PublicKey,
    /// The ephemeral public key R (embedded in tx calldata so the relayer can find it).
    pub ephemeral_pubkey: PublicKey,
}

impl RelayerKeys {
    /// Generate a new random relayer key pair.
    pub fn generate<R: rand::CryptoRng + rand::RngCore>(rng: &mut R) -> Self {
        let spend_privkey = SecretKey::random(rng);
        let spend_pubkey = spend_privkey.public_key();
        let view_privkey = SecretKey::random(rng);
        let view_pubkey = view_privkey.public_key();
        Self {
            spend_privkey,
            spend_pubkey,
            view_privkey,
            view_pubkey,
        }
    }

    /// Construct from existing secret key bytes.
    pub fn from_privkeys(spend: &[u8; 32], view: &[u8; 32]) -> Result<Self, k256::elliptic_curve::Error> {
        let spend_privkey = SecretKey::from_slice(spend)?;
        let spend_pubkey = spend_privkey.public_key();
        let view_privkey = SecretKey::from_slice(view)?;
        let view_pubkey = view_privkey.public_key();
        Ok(Self {
            spend_privkey,
            spend_pubkey,
            view_privkey,
            view_pubkey,
        })
    }

    /// Compute the stealth private key for a detected stealth transfer.
    /// stealth_privkey = hash(shared_secret) + spend_privkey
    pub fn stealth_private_key(&self, ephemeral_pubkey: &PublicKey) -> SecretKey {
        let shared_secret = compute_shared_secret(&self.view_privkey, ephemeral_pubkey);
        let hash_scalar = secret_to_scalar(&shared_secret);
        let spend_scalar = scalar_from_secret(&self.spend_privkey);
        let stealth_scalar = hash_scalar + spend_scalar;
        SecretKey::from_slice(&stealth_scalar.to_bytes()).expect("valid scalar sum")
    }
}

impl EphemeralKeys {
    /// Generate a new random ephemeral keypair.
    pub fn generate<R: rand::CryptoRng + rand::RngCore>(rng: &mut R) -> Self {
        let privkey = SecretKey::random(rng);
        let pubkey = privkey.public_key();
        Self { privkey, pubkey }
    }

    /// Construct from existing secret key bytes.
    pub fn from_privkey(key: &[u8; 32]) -> Result<Self, k256::elliptic_curve::Error> {
        let privkey = SecretKey::from_slice(key)?;
        let pubkey = privkey.public_key();
        Ok(Self { privkey, pubkey })
    }
}

/// Derive stealth address from a pre-computed shared secret and relayer spend pubkey.
fn derive_stealth_address_from_secret(
    shared_secret: &[u8; 32],
    relayer_spend_pubkey: &PublicKey,
    ephemeral_pubkey: &PublicKey,
) -> StealthAddress {
    let hash_scalar = secret_to_scalar(shared_secret);
    let hash_point = ProjectivePoint::GENERATOR * hash_scalar;
    let spend_point = ProjectivePoint::from(*relayer_spend_pubkey.as_affine());
    let stealth_point = hash_point + spend_point;

    let stealth_pubkey = PublicKey::from_affine(stealth_point.to_affine()).expect("valid point");
    let address = pubkey_to_eth_address(&stealth_pubkey);

    StealthAddress {
        address,
        stealth_pubkey,
        ephemeral_pubkey: *ephemeral_pubkey,
    }
}

/// Compute ECDH shared secret: keccak256(privkey * pubkey compressed encoding).
fn compute_shared_secret(privkey: &SecretKey, pubkey: &PublicKey) -> [u8; 32] {
    let scalar = scalar_from_secret(privkey);
    let point = ProjectivePoint::from(*pubkey.as_affine()) * scalar;
    let affine = point.to_affine();
    let encoded = affine.to_bytes(); // compressed SEC1 encoding
    keccak256(&encoded)
}

/// Hash a shared secret to a scalar for stealth key derivation.
fn secret_to_scalar(secret: &[u8; 32]) -> Scalar {
    use k256::elliptic_curve::ops::Reduce;
    let wide = k256::U256::from_be_slice(secret);
    Scalar::reduce(wide)
}

/// Extract the scalar value from a SecretKey.
fn scalar_from_secret(key: &SecretKey) -> Scalar {
    *key.to_nonzero_scalar()
}

/// Convert a secp256k1 public key to an Ethereum address.
/// address = last 20 bytes of keccak256(uncompressed_pubkey_bytes[1..])
pub fn pubkey_to_eth_address(pubkey: &PublicKey) -> [u8; 20] {
    let encoded = pubkey.to_encoded_point(false); // uncompressed: 0x04 || x || y
    let bytes = encoded.as_bytes();
    // Skip the 0x04 prefix
    let hash = keccak256(&bytes[1..]);
    let mut addr = [0u8; 20];
    addr.copy_from_slice(&hash[12..]);
    addr
}

/// Keccak256 hash.
pub fn keccak256(data: &[u8]) -> [u8; 32] {
    let mut hasher = Keccak::v256();
    let mut output = [0u8; 32];
    hasher.update(data);
    hasher.finalize(&mut output);
    output
}

// ─── Public API ──────────────────────────────────────────────────────────────

/// User-side: generate a stealth address for a relayer.
/// Returns (StealthAddress, shared_secret) — the shared_secret is needed to encrypt instructions.
pub fn user_generate_stealth(
    relayer_spend_pubkey: &PublicKey,
    relayer_view_pubkey: &PublicKey,
    ephemeral_keys: &EphemeralKeys,
) -> (StealthAddress, [u8; 32]) {
    let shared_secret = compute_shared_secret(&ephemeral_keys.privkey, relayer_view_pubkey);
    let stealth = derive_stealth_address_from_secret(
        &shared_secret,
        relayer_spend_pubkey,
        &ephemeral_keys.pubkey,
    );
    (stealth, shared_secret)
}

/// Relayer-side: check if an ephemeral pubkey corresponds to a stealth address for this relayer.
/// Returns Some((StealthAddress, shared_secret)) if matched.
pub fn relayer_check_stealth(
    relayer_keys: &RelayerKeys,
    ephemeral_pubkey: &PublicKey,
    tx_recipient: &[u8; 20],
) -> Option<(StealthAddress, [u8; 32])> {
    let shared_secret = compute_shared_secret(&relayer_keys.view_privkey, ephemeral_pubkey);
    let stealth = derive_stealth_address_from_secret(
        &shared_secret,
        &relayer_keys.spend_pubkey,
        ephemeral_pubkey,
    );
    if stealth.address == *tx_recipient {
        Some((stealth, shared_secret))
    } else {
        None
    }
}

/// Relayer-side: recover the stealth private key to spend funds from a stealth address.
pub fn relayer_recover_stealth_privkey(
    relayer_keys: &RelayerKeys,
    ephemeral_pubkey: &PublicKey,
) -> SecretKey {
    relayer_keys.stealth_private_key(ephemeral_pubkey)
}

// ─── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use rand::rngs::OsRng;

    #[test]
    fn test_key_generation() {
        let keys = RelayerKeys::generate(&mut OsRng);
        assert_eq!(keys.spend_pubkey, keys.spend_privkey.public_key());
        assert_eq!(keys.view_pubkey, keys.view_privkey.public_key());
        assert_ne!(
            keys.spend_privkey.to_bytes(),
            keys.view_privkey.to_bytes()
        );
    }

    #[test]
    fn test_shared_secret_agreement() {
        // Both sides of ECDH must produce the same shared secret:
        // user: ECDH(ephemeral_priv, view_pub) == relayer: ECDH(view_priv, ephemeral_pub)
        let relayer = RelayerKeys::generate(&mut OsRng);
        let ephemeral = EphemeralKeys::generate(&mut OsRng);

        let user_secret = compute_shared_secret(&ephemeral.privkey, &relayer.view_pubkey);
        let relayer_secret = compute_shared_secret(&relayer.view_privkey, &ephemeral.pubkey);

        assert_eq!(user_secret, relayer_secret);
    }

    #[test]
    fn test_stealth_address_derivation() {
        // User derives a stealth address; relayer should detect it.
        let relayer = RelayerKeys::generate(&mut OsRng);
        let ephemeral = EphemeralKeys::generate(&mut OsRng);

        let (stealth, _) = user_generate_stealth(
            &relayer.spend_pubkey,
            &relayer.view_pubkey,
            &ephemeral,
        );

        let result = relayer_check_stealth(&relayer, &ephemeral.pubkey, &stealth.address);
        assert!(result.is_some(), "Relayer should detect its own stealth address");

        let (matched, _) = result.unwrap();
        assert_eq!(matched.address, stealth.address);
    }

    #[test]
    fn test_stealth_private_key_recovery() {
        // The relayer-recovered private key should correspond to the stealth public key.
        let relayer = RelayerKeys::generate(&mut OsRng);
        let ephemeral = EphemeralKeys::generate(&mut OsRng);

        let (stealth, _) = user_generate_stealth(
            &relayer.spend_pubkey,
            &relayer.view_pubkey,
            &ephemeral,
        );

        let recovered_privkey = relayer_recover_stealth_privkey(&relayer, &ephemeral.pubkey);
        let recovered_pubkey = recovered_privkey.public_key();

        assert_eq!(
            recovered_pubkey, stealth.stealth_pubkey,
            "Recovered private key should correspond to stealth public key"
        );

        let recovered_addr = pubkey_to_eth_address(&recovered_pubkey);
        assert_eq!(recovered_addr, stealth.address);
    }

    #[test]
    fn test_deterministic_output_for_fixed_seed() {
        let spend_bytes: [u8; 32] = [1u8; 32];
        let view_bytes: [u8; 32] = [2u8; 32];
        let ephemeral_bytes: [u8; 32] = [3u8; 32];

        let relayer = RelayerKeys::from_privkeys(&spend_bytes, &view_bytes).unwrap();
        let ephemeral = EphemeralKeys::from_privkey(&ephemeral_bytes).unwrap();

        let (stealth1, secret1) = user_generate_stealth(
            &relayer.spend_pubkey,
            &relayer.view_pubkey,
            &ephemeral,
        );

        let (stealth2, secret2) = user_generate_stealth(
            &relayer.spend_pubkey,
            &relayer.view_pubkey,
            &ephemeral,
        );

        assert_eq!(stealth1.address, stealth2.address);
        assert_eq!(secret1, secret2);
    }

    #[test]
    fn test_different_ephemeral_keys_produce_different_addresses() {
        let relayer = RelayerKeys::generate(&mut OsRng);
        let eph1 = EphemeralKeys::generate(&mut OsRng);
        let eph2 = EphemeralKeys::generate(&mut OsRng);

        let (s1, _) = user_generate_stealth(&relayer.spend_pubkey, &relayer.view_pubkey, &eph1);
        let (s2, _) = user_generate_stealth(&relayer.spend_pubkey, &relayer.view_pubkey, &eph2);

        assert_ne!(s1.address, s2.address, "Different ephemeral keys must produce different stealth addresses");
    }

    #[test]
    fn test_wrong_relayer_does_not_detect() {
        let relayer1 = RelayerKeys::generate(&mut OsRng);
        let relayer2 = RelayerKeys::generate(&mut OsRng);
        let ephemeral = EphemeralKeys::generate(&mut OsRng);

        let (stealth, _) = user_generate_stealth(
            &relayer1.spend_pubkey,
            &relayer1.view_pubkey,
            &ephemeral,
        );

        let result = relayer_check_stealth(&relayer2, &ephemeral.pubkey, &stealth.address);
        assert!(result.is_none(), "Wrong relayer should not detect another relayer's stealth address");
    }

    #[test]
    fn test_eth_address_format() {
        let relayer = RelayerKeys::generate(&mut OsRng);
        let ephemeral = EphemeralKeys::generate(&mut OsRng);

        let (stealth, _) = user_generate_stealth(
            &relayer.spend_pubkey,
            &relayer.view_pubkey,
            &ephemeral,
        );

        assert_eq!(stealth.address.len(), 20);
        assert_ne!(stealth.address, [0u8; 20]);
    }
}
